apiVersion: v1
kind: Secret
metadata:
  name: sensor-threshold-mapping-service-secret
  namespace: flet-montrg
  labels:
    app: sensor-threshold-mapping-service
type: Opaque
data:
  DATABASE_URL:   # base64 encoded
