apiVersion: v1
kind: ConfigMap
metadata:
  name: web-service-config
  namespace: flet-montrg
  labels:
    app: web-service
data:
  APP_NAME: "Flet Montrg Web (API Gateway UI)"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
