apiVersion: v1
kind: Secret
metadata:
  name: alert-subscription-service-secret
  namespace: flet-montrg
  labels:
    app: alert-subscription-service
type: Opaque
data:
  DATABASE_URL:  # base64 encoded
